on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksjuice.azurecr.io
        username: ${{ secrets.acr_aksjuice_username }}
        password: ${{ secrets.acr_aksjuice_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aksjuice.azurecr.io/uclkedaaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push aksjuice.azurecr.io/uclkedaaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_uclkedaaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep uclkedaaks8674 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace uclkedaaks8674`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: uclkedaaks8674
        container-registry-url: aksjuice.azurecr.io
        container-registry-username: ${{ secrets.acr_aksjuice_username }}
        container-registry-password: ${{ secrets.acr_aksjuice_password }}
        secret-name: uclkedaaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: uclkedaaks8674
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          aksjuice.azurecr.io/uclkedaaks:${{ github.sha }}
        imagepullsecrets: |
          uclkedaaksdockerauth
